### ISSUE TITLE
Unsuffixed methods should return result instead of panicking

### ISSUE THREAD

**Issue by e-oz** [chronotope/chrono#110]
It's not the end of the world - please return some kind of error.

```
thread 'main' panicked at 'No such local time', chrono-0.2.25/src/offset/mod.rs:151
```

**Comment by lifthrasiir** [comment]
You are supposed to use [`chrono::offset::LocalResult`](http://lifthrasiir.github.io/rust-chrono/chrono/offset/enum.LocalResult.html) when the error is expected. In particular it is the mandatory when you are accepting a date and time from untrusted sources.

**Comment by lifthrasiir** [comment]
Thinking more about this, this might be signalling needs for the NaN-ish value for DateTime... which I don't like to add (precisely for the reasons same to NaN) though. I'm just noting a potential solution here and my suggestion is still to use `LocalOffset` and `*_opt` family of methods.

**Comment by e-oz** [comment]
it's the result of DateTime::timestamp method - not obvious how to use LocalResult in this case.

Panicking is not idiomatic way. "_opt" methods is a possible workaround to not break API, but to be fair, if function has chance to return error, it should return result either in Result or in Option.

**Comment by matt2xu** [comment]
I find it also a bit surprising that many methods can panic. I would expect to see methods returning a Result with a reason why an operation on a date/time fails, or alternatively a JavaScript-like solution where dates/times are automatically fixed. This is what is good about pre-1.0 crates: the API can change if you want

**Comment by quodlibetor** [comment]
@e-oz there has been a `timestamp_opt` method on `DateTime` objects for as long as there has been a `timestamp` method, that is the method that will not panic.

@matt2xu we could hypothetically replace the various methods with their `*_opt`-equivalents, and add `*_unchecked` methods, but:

1. The `*_unchecked` idiom usually refers to memory safety, we'd probably want something different for panic safety.
2. I think that there are reasonable arguments to be made in both directions, the biggest one in favor of the status quo is ergonomics: in every case that _I've_ needed these methods for panic-on-error has been reasonable, or at least I've never been bit by it. It does feel a bit icky, though.

**Comment by quodlibetor** [comment]
Thinking about this, I think that my previous response was wildly, just.. wildly, wrong. It doesn't make sense to have fallible operations that depend on program input that panic in the obvious case.

Assuming we want to migrate to an API that returns results in significantly more places the question becomes how do we want to migrate, without making the entire rust ecosystem more annoyed.

I'm thinking that it might make sense to leave the current impl alone, define a couple new traits based on the wrapping/saturating numeric types (e.g. `TimelikePanicking` and `Timelike`?) that describe the current methods (with interface changes for `Timelike` so that it returns results) so that the migration can be pretty easy for most users (just need to import the back-compat trait) but we can get to a more rusty API by default.

**Comment by budziq** [comment]
I for one would opt for `checked_*` fammily of functions to return `Result<Duration, OutOfRangeError>` or whatnot instead of `Option` but i understand that we are trying to follow the checked arithmetic of integral types in std.

**Comment by galich** [comment]
TLTR; panics are not acceptable, we need a solution to this.

`chrono` is quite widespread and it's using deprecated `time` crate, which panics on invalid values. I'm having real world crashes because some of the data is corrupted. It happens on user machines and due to reasons I can't ask for a dump or even a stack trace.

**Comment by pitdicker** [comment]
Closing in favor of https://github.com/chronotope/chrono/issues/1049. We have non-panicking alternatives to almost all methods now, and making them default for 0.5 is definitely on the roadmap.
