### ISSUE TITLE
Behavior change in 0.4.31 with timestamp_opt method

### ISSUE THREAD

**Issue by whiskeyjay** [chronotope/chrono#1300]
Hi folks,

The following test used to pass, but now fails with 0.4.31. Is this a bug or part of the intended fix as listed in the 0.4.31 release notes?

Thanks!

```Rust
#[cfg(test)]
mod tests {
    use chrono::{self, TimeZone};

    #[test]
    fn test_timestamp_opt() {
        let datetime_bytes = [255, 255, 255, 255, 255, 255, 255, 255];
        let datetime_number = u64::from_be_bytes(datetime_bytes);

        assert_eq!(18446744073709551615, datetime_number);

        assert_eq!(
            "2514-05-30 01:53:04.073741823 UTC",
            match chrono::Utc.timestamp_opt(
                datetime_number as i64 & 0x00000003ffffffff,
                (datetime_number >> 34) as u32
            ) {
                chrono::LocalResult::Single(datetime) => datetime.to_string(),
                _ => "".to_string(),
            }
        );
    }
}
```

**Comment by pitdicker** [comment]
Thank you for the report. I'll look into it.
Reduces test:
```rust
#[test]
fn test_timestamp_opt() {
    let secs = 0x3ffff_ffff;
    let nanos = 0x3fff_ffff;
    assert_eq!(
        "2514-05-30 01:53:04.073741823 UTC",
        Utc.timestamp_opt(secs, nanos).unwrap().to_string()
    );
    assert_eq!(
        "2514-05-30 01:53:04.073741823 UTC",
        NaiveDateTime::from_timestamp_opt(secs, nanos).unwrap().and_utc().to_string()
    );
}
```

**Comment by pitdicker** [comment]
The issue is that the nanosecond argument is `0x3fff_ffff` or `1_073_741_823`.
For most values it should be in the range `0..1_000_000_000`.

We used to allow values in `1_000_000_000..2_000_000_000` to represent leap seconds, but became a little stricter and now check if a leap seconds falls on a minute boundary.

As an example `Utc.timestamp_opt(0x3_ffff_ffff, 1_000_000).unwrap().to_string()` and `Utc.timestamp_opt(0x4_000_000, 0).unwrap().to_string()` would print the same value, while being different datetimes.

In this issue `Utc.timestamp_opt(0x3ffff_ffff, 0)` would create the datetime `"2514-05-30 01:53:03 UTC"`, and `"1.073741823"` is what gets added by the nanosecond component to represent a leap second.

Because leap seconds that don't fall on a minute boundary don't exist, and chrono making it easy to create them anyway caused confusion, we have now prevent creating them in initialization methods.
