### ISSUE TITLE
Steady clocks?

### ISSUE THREAD

**Issue by phaazon** [chronotope/chrono#133]
I followed the link on the `time` crate to end up here, as `time` is being deprecated. Though, I don’t find the similar clock for `SteadyTime`. :(

**Comment by lifthrasiir** [comment]
If you are finding a replacement for `SteadyTime` you are *not* concerned of the wall clock but of the opaque monotonic clock, which is exactly a job of [`std::time::Instant`](https://doc.rust-lang.org/std/time/struct.Instant.html). Chrono is strictly about the calendar time.

**Comment by phaazon** [comment]
Oh! Thank you! The message on the `time` repo misleaded me. So, are you saying that `std::time::Instant` has enough precision to be a replacement of `time::SteadyTime`?

**Comment by lifthrasiir** [comment]
@phaazon

The terminology here is interesting, but I think `time::SteadyTime` itself was _not_ steady in terms of `std::time::Instant`'s language. In fact it can be extremely hard (if not impossible) to ensure that each tick is of the equal length, because the [real-time clock](https://en.wikipedia.org/wiki/Real-time_clock) itself can have variance (±1ppm variance is within the expectation). I guess you will never have this kind of requirements :-)

In all practical purpose the "steady" clock is meant to refer to the monotonic clock, implicitly thought to be unable to alter (this is why C++'s [`std::steady_clock`](https://stackoverflow.com/questions/6777278/what-is-the-rationale-for-renaming-monotonic-clock-to-steady-clock-in-chrono) was named so). There should be no actual difference.

**Comment by phaazon** [comment]
Thanks!
