### ISSUE TITLE
Index out of bounds: the len is 733 but the index is 798

### ISSUE THREAD

**Issue by zr-mah** [chronotope/chrono#1517]
Hi, 

We are getting this panic message with 0.4.35 version
![image](https://github.com/chronotope/chrono/assets/23479560/71ecc013-ab5c-419d-93b0-f8b598c7c595)

From the code that causes the error mentioned about leapyear. and this year is leap year.

![image](https://github.com/chronotope/chrono/assets/23479560/517fa939-2037-494d-952b-c1ad0002e61d)

Much help is appreciated

**Comment by djc** [comment]
Do you have a minimal reproducing example?

**Comment by pitdicker** [comment]
Or a backtrace, or the method you are calling?

**Comment by pitdicker** [comment]
The index out of bounds here means that some function in chrono was able to construct a `NaiveDate` with 399 as ordinal. Not idea which function yet.

**Comment by pitdicker** [comment]
To describe a bit more of what is happening.

Somehow somewhere an invalid `NaiveDate` is created. At some later point this causes an index out of bounds panic. So a backtrace is probably not going to help.

We have exactly a dozen places where a `NaiveDate` is created. All have to pass through [`NaiveDate::from_yof`](https://github.com/chronotope/chrono/blob/v0.4.35/src/naive/date/mod.rs#L1442).
So I'll see if there is something amiss in any of the 12 locations.

If @zr-mah can come up with a minimal reproducing example is that would help pinpoint the problematic method. Otherwise if I can't find it by eye and tests we can extra debug asserts in `NaiveDate::from_yof` and see what that trips up.

**Comment by zypeh** [comment]
@pitdicker *False alarm* . We have run a series of test with both chrono 0.4.34 and 0.4.35 but we couldn't simulate the bug. Strange, but it is not working on production end-to-end tests. After spending some time to investigate, we found the issue:

1. we are parsing sane millisecond timestamp u64 can to something like '0003-00-00T19:33:20.016581814Z'. (Which is the time when Jesus is 3 years old). So i suspect it is integer overflow during the parsing.

2. In production we are using `rkyv` to transfer the struct contains `Datetime<Utc>`, and we have tested it locally, the result is correct.

3. After checking the Cargo.lock we found that in production environment some of the client that deserialise `rkyv` to the struct containing `Datetime<Utc>` is using latest chrono `0.4.35`. But the server is serialising using chrono `0.4.34`.

So it is because of the *version mismatch between server-client when using rkyv*.

Then why is rkyv not complaining when there is a version mismatch and let this happen? I think it is due to we are using 
`rkyv::from_bytes_unchecked(&bytes[..read_len]).unwrap()` the unsafe version to deserialise data between two projects. So after locking the version in those client to using chrono `0.4.34`. The result is correct. Thanks for the active replies from all of you. ❤️

**Comment by zr-mah** [comment]
Thank you very much @pitdicker for all your help! It was indeed helpful so that we were able to pinpoint that it could be something not related to chrono!

**Comment by pitdicker** [comment]
We did a refactor of the `naive::date` and `naive::internals` modules in 0.4.35. Can you please double-check that we did not make a mistake with 0.4.35?
Nothing is changed in the internal representation, so I think `rkyv` shouldn't be the cause of the problem.

**Comment by zypeh** [comment]
@pitdicker Yes but I see you have changes in `naive::internals` in 0.4.35. But in this case we are serialising it via 0.4.34 and deserialise it via 0.4.35 somewhere else.

So maybe I can help you to check when we bump our rkyv serialiser to use chrono 0.4.35?

**Comment by pitdicker** [comment]
If it helps this https://github.com/chronotope/chrono/tree/oob_panic branch adds a few more extra checks that should give a helpful backtrace.

**Comment by pitdicker** [comment]
One more question: Did you happen to wrap the `DateTime` in an `Option` when serializing with rkyv? Because our date types got niche optimization with 0.4.35, and that could change the format.

**Comment by zypeh** [comment]
@pitdicker No we didn't wrap it with `Option`.
