### ISSUE TITLE
Add support for locales in format

### ISSUE THREAD

**Issue by antoyo** [chronotope/chrono#153]
Hello.
It would be nice to be able to format a date in other languages than english.
Thanks to add this feature.

**Comment by Cobrand** [comment]
I don't think it will be implemented directly in Chrono's core, however it could easily implemented as an optional feature (in the Rust sense), or even as another crate entirely. The latter would make much more sense, as it would be exactly like [chrono-humanize](https://crates.io/crates/chrono-humanize) did.

**Comment by lifthrasiir** [comment]
In addition to being out of scope, date and time localization is about as difficult as time zone, because we may have to handle different chronologies at that point (e.g. [Japanese era names](https://en.wikipedia.org/wiki/Japanese_calendar) or [Islamic calendar](https://en.wikipedia.org/wiki/Islamic_calendar)). We probably have to delegate the entire jobs to something like [rust-locale](https://github.com/rust-locale/rust-locale).

**Comment by hjmallon** [comment]
Coming from C/C++ it seems confusing to have a non locale-aware function called strftime. C languages and Python seem to translate day/month/etc names automatically along with preferred ordering and (in C) Japanese eras etc.

A few of these issues talk about a separate crate or fluent. Does anyone know where/if this functionality is supported or is aiming to be supported?

**Comment by cecton** [comment]
I updated #199 with a proposal for this issue.
