### ISSUE TITLE
str parse date with single digits

### ISSUE THREAD

**Issue by glennpierce** [chronotope/chrono#155]
Hi as a test I am trying to parse a date time in the format

"1/1/06 0:00"
month/day/year  time

The single digits are causing issues I think.

what is the format for parsing this ?

I have tried lots of versions using 
https://docs.rs/chrono/0.3.1/chrono/format/strftime/index.html
now but can't work it out

DateTime::parse_from_str("1/1/06 0:00", "%D %k:%M").unwrap();

Thanks

**Comment by glennpierce** [comment]
OK after more playing I can parse using

NaiveTime::parse_from_str("0:00:00", "%H:%M:%S").unwrap();
NaiveTime::parse_from_str("0:00:00", "%T").unwrap();
NaiveDate::parse_from_str("1/1/06", "%D").unwrap();
NaiveDateTime::parse_from_str("1/1/06 0:00", "%D %H:%M").unwrap();

Main issue was having to use NaiveDateTime

Without knowing the Chrono internal I think DateTime::parse_from_str("1/1/06 0:00", "%D %H:%M").unwrap();
should just work in cases like this maybe assume UTC

**Comment by lifthrasiir** [comment]
(Sorry for very delayed reply :S)

This is not because of the single digit. This is rather the fact that `DateTime<FixedOffset>` (which is the return type of `DateTime::parse_from_str`) always requires time zones so you need some offset information to get the full `DateTime<FixedOffset>`.

There are generally two different ways to resolve the problem. One is, as described above, to use the explicit offset in the input:

```rust
DateTime::parse_from_str("1/1/06 0:00 +0000", "%D %H:%M %z").unwrap();
```

Another is to clearly indicate that we will interpret the input as UTC.

```rust
Utc.datetime_from_str("1/1/06 0:00", "%D %H:%M").unwrap(); // note: used to be UTC in 0.3
```
