### ISSUE TITLE
Chrono 0.3.1 breaks backwards compatibility with Chrono 0.3.0

### ISSUE THREAD

**Issue by Razican** [chronotope/chrono#156]
I am using Rocket 0.2.8, and for that, I need to use Serde 0.9 (for now). It worked great with chrono 0.3.0, but chrono 0.3.1 updates to Serde 1.0, which breaks backwards compatibility.

**Comment by SergioBenitez** [comment]
Indeed. @lifthrasiir, dcf193323b59b8c85f0be708d5ba2b6a1a1654d2 should have bumped the chrono version to `0.4`. As it stands, semantic versioning has been broken, and any applications using chrono `0.3` are liable to break as a result. I'd recommend yanking chrono `0.3.1` and publishing `0.4` with the serde `1.0` upgrade.

**Comment by quodlibetor** [comment]
related to #146 , where @lifthrasiir has commented.

FWIW I agree that having a semver-incompatible change in a patch release is an issue, especially since serde 1.0 already splits the ecosystem, it's easier to manage dependencies if chrono 0.4 is serde-1.0 compatible and chrono 0.3 is serde 0.9 compatible.

**Comment by durka** [comment]
This broke my code as well. I've submitted a PR to fix the issue.

**Comment by SergioBenitez** [comment]
@lifthrasiir Can you comment and/or remedy the situation?

**Comment by durka** [comment]
@SergioBenitez see https://github.com/chronotope/chrono/issues/146#issuecomment-309276715
