### ISSUE TITLE
Releases has problematic naming of 0.4.8 release which puts it at the top

### ISSUE THREAD

**Issue by doivosevic** [chronotope/chrono#1568]
I guess a "v" is missing so it gets put at the top
https://github.com/chronotope/chrono/releases

![image](https://github.com/chronotope/chrono/assets/6378638/ad194fa5-4f1f-46b3-b8d3-749841e79424)

**Comment by pitdicker** [comment]
I'll check to make sure they all start with a 'v'.

In this case the problem is caused by me changing the tag of 4.8 to a different commit to match the crates.io release. See https://github.com/chronotope/chrono/issues/1564.

GitHub sorts the releases by date of the tags. Maybe I can change the date...

**Comment by pitdicker** [comment]
Hmm. No, in this case the 0.4.8 release had a small accident and did not end up on the main branch. I suppose that just confuses GitHub. Not sure if there is anything I can do.

**Comment by djc** [comment]
It'll drift down again, this really doesn't seem like a big deal.
