### ISSUE TITLE
Add support for subtracting DateTime<Tz>

### ISSUE THREAD

**Issue by JoeyAcc** [chronotope/chrono#168]
At the moment the [DateTime documentation](https://docs.rs/chrono/0.4.0/chrono/struct.DateTime.html) shows me that there is an impl to subtract `DateTime<FixedOffset>` instances from one another to obtain a `Duration` instance that describes the time delta.

What doesn't seem to be possible is to do something like this:
```` rust
extern crate chrono;
use chrono::prelude::*;

fn foo() {
    let start: DateTime<Local> = Local::now();
    let end: DateTime<Local> = Local::now();
    let dur = end - start; // Error: `std::ops::Sub` not implemented for `chrono::DateTime<chrono::Local>`
}
````

What I would like to be able to do is such a subtraction in general for `DateTime<Tz>`, for any `Tz` type param. Ideally it would even be possible to subtract e.g. a `DateTime<Local>` from a `DateTime<Utc>` and have the time zone conversion done internally in the `std::ops::Sub`.

Could this be implemented, or is there some kind of restriction that prevents this?

**UPDATE**: I just found the `dt0.signed_duration_since(dt1)` method, which does what I need.  However, if the possibility exists to implement the `Sub` trait, I'd still like that to happen as it would be a more intuitive way to access that functionality.

**Comment by quodlibetor** [comment]
I can't see an obvious reason _not_ to `impl<T> Sub<DateTime<T>> for DateTime<T>` in terms of `signed_duration_since`, except that `Sub` "normally" returns the same type as its operands. I can't imagine people wanting to do `Date(2000) - Date(1970)` and end up with 30CE, though.

Doing it for multiple timezones seems like it would open up accidental cases where people didn't realize they were working with different Tzs, and I think that it would be better to force people to go to Utc with both sides first. If that turns out to be onerous and not actually be preventing we could add in a more general Sub impl later.

**Comment by alexchandel** [comment]
@quodlibetor Having `Sub` return a different type makes sense here. Dates (as viewed by `chrono`) are elements of an affine space. Subtraction between two points in an affine space is well-defined, but it doesn't yield another affine point. Instead it yields an element of the associated vector space (i.e. durations for `chrono`). And just as elements of the associated vector space should be able to be added to (or subtracted from) affine elements to yield new affine elements, so can durations be added to dates in `chrono`.

Notably, the addition of elements of an affine space isn't well-defined, and similarly the addition of two `DateTime`s is meaningless in `chrono`.

**Comment by Enet4** [comment]
@iamsebastian It seems to work fine with 0.4.2, though ([minimal example](https://play.rust-lang.org/?gist=04a2178e5e885c092ece502d2f9d1acc&version=stable&mode=debug)). It's odd that the functionality appears with a patch version bump, so it might be a bug in that specific version. Can you force a dependency update and try again?

**Comment by Enet4** [comment]
I would actually take back part of what I just said. I am not quite up to date on why this particular feature disappeared in 0.4.0, so I cannot claim this to be a bug. This is actually compliant with semver: the implementation disappeared with a new pre-release, which can have breaking changes, and subsequent patch versions can then add new features as long as it's compatible with the corresponding pre-release's minor version. Why this used to work in 0.2.x and not until 0.4.2, I do not quite know. :man_shrugging:

**Comment by quodlibetor** [comment]
I believe (though I'm not confident) it was removed in 0.3.0 because of a sweeping api redesign, and 0.4.2 added it back.

And, yes, in the Rust ecosystem patch/z-level bumps of 0.x.z crates do typically introduce new features, while minor/x-level version bumps are reserved for backcompat issues. This is mostly because of the way that cargo treats semver before you hit 1.0.
