### ISSUE TITLE
Convience method for converting from DateTime<FixedOffset> to UTC

### ISSUE THREAD

**Issue by glennpierce** [chronotope/chrono#169]
Hi

Currently I am doing something like

let dt : DateTime<FixedOffset> = DateTime::parse_from_rfc3339("1970-01-01T00:00:00+00:00")?;
let dt_utc : DateTime<UTC> = DateTime::<UTC>::from_utc(dt.naive_utc(), UTC);

Is there any more convenient way todo this and vice versa ?

Thanks

**Comment by quodlibetor** [comment]
The fact that `Utc` is a type (and therefore can't depend on anything at run-time) means that it's impossible for methods on `DateTime<FixedOffset>` (which is where the `parse_from_rfc3339` is implemented) to parse to a `DateTime<Utc>`. 

However, we could probably implement either a `DateTime<Utc>::parse_from_rfc3339()` (or probably nicer a `Utc::parse_from_rfc3339()`) that does the parsing and auto-timezone conversion. 

Doing _that_ depends a bit on the philosophical outlook of this trait: whether we want to implement a whole bunch of kind-of-trivial ergonomic methods or if we want to keep the API surface small. We're currently thinking about the tradeoffs of the two philosophies.

**Comment by glennpierce** [comment]
Thanks

**Comment by nathanaeljones** [comment]
I've spent about 30 minutes trying to figure out how to correctly convert between DateTime<Utc> and DateTime<FixedOffset>.  I strongly support making that conversion more ergonomic.

**Comment by Walther** [comment]
If a convenience method (e.g. `FixedOffset::now()`) would not be feasible, maybe the documentation could be improved? On a quick reading, the Readme seems to warmly suggest using `FixedOffset` as "it stores the most information and does not depend on the system environment". However, there's no instruction / example on how to properly use it.

**Comment by djc** [comment]
I'm going to close this issue. The original request has been addressed with #806 in that you can now call `parse_from_rfc3339()` on `DateTime<Utc>`. Additionally, an `impl From<DateTime<FixedOffset>> for DateTime<Utc>` already exists.

However, I'm definitely open to the idea that ergonomic issues still exist here! In order to address those, please open a new issue with some example code of where you're running into trouble/a conversion that seems to require more complex code than what you feel is necessary.
