### ISSUE TITLE
Give `to_rfc3339` a param: number of fractional second digits

### ISSUE THREAD

**Issue by sanmai-NL** [chronotope/chrono#171]
https://docs.rs/chrono/0.4.0/chrono/struct.DateTime.html#method.to_rfc3339 has no parameters, but with some applications too long a string of digits isn't expected (e.g., [on the web](https://www.feedvalidator.org/docs/error/InvalidRFC3339Date.html)), however, `to_rfc3339` currently emits such long strings (e.g. `959686092`).

https://www.ietf.org/rfc/rfc3339.txt seems to prescribe one digit only for the fractional seconds, so perhaps the current implementation is in error? If for practical reasons the number of fractional second digits should be tunable irrespective of the official grammar, then I propose that the range be between 0 (in which case the decimal separator isn't emitted) and, say, 16 (to be determined).

**Comment by quodlibetor** [comment]
I think that you're reading the ABNF specified in RFC 3339 incorrectly, [it says that the internet date/time format is](https://tools.ietf.org/html/rfc3339#section-5.6):

```
...
   time-secfrac    = "." 1*DIGIT
...
   partial-time    = time-hour ":" time-minute ":" time-second
                     [time-secfrac]
...
   full-time       = partial-time time-offset
...
   date-time       = full-date "T" full-time
```

That `1*DIGIT` _looks_ like it's saying that there should be one digit, but it's actually a [variable repetition rule](https://tools.ietf.org/html/rfc2234#section-3.6):

```
   The operator "*" preceding an element indicates repetition. The full
   form is:

        <a>*<b>element

   where <a> and <b> are optional decimal values, indicating at least
   <a> and at most <b> occurrences of element.
```

So the current implementation is definitely correct, and in fact the feed validator [link you provided](https://www.feedvalidator.org/docs/error/InvalidRFC3339Date.html) includes an example with multiple digits in the fraction of the datetime `2002-10-02T15:00:00.05Z`.

This is, though, I think related to #165, in that we'd like to be able to have multiple ways of displaying the fractional portion of a time.

**Comment by sanmai-NL** [comment]
Well I hoped to convery I wasn't so sure about the grammar at all, only took a quick look.

Some background into the jungle of date time notations ...
> Several standards and profiles have been derived from ISO 8601, including RFC 3339 and a W3C note on date and time formats.

(Source: https://www.cl.cam.ac.uk/~mgk25/iso-time.html#software)

The `lastmod` attribute in XML sitemaps contains [W3C timestamps](https://www.w3.org/TR/NOTE-datetime) according to [sitemaps.org](https://www.sitemaps.org/protocol.html), which are highly similar to RFC 3339 timestamps. The sitemaps.org reference provides [a validation XSD](https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd), which uses the `xsd:dateTime` type for this attribute. This `xsd:dateTime` type [does not allow](http://books.xmlschemata.org/relaxng/ch19-77049.html) for fractional second digits, however.

Regardless, a simple starting point for formatting the fractional second as in #165 is in allowing a choice of number of digits and presence.

**Comment by quodlibetor** [comment]
Yeah, I think it'd be nice to expand the [`%.Nf` specifier](https://docs.rs/chrono/0.4.0/chrono/format/strftime/index.html) to any `N` between 0 and 9 (inclusive), instead of the current "3, 6, 9" options, in addition to the proposed `-`/`#` "minimum number of digits without loosing precision" operator.

There are, unfortunately, way too many "specifications" for datetime formats for us to be able to handle them all, I think. As you've noticed RFC 3339 (by the IETF) isn't interchangeable even with a specification put out by the W3C!

I am currently of the opinion that that RFC 3339 is the correct format to serialize/deserialize from by default, since it's (A) very well specified, with the only optional portion being the fractional second specification and (B) what people generally think of when they think of ISO 8601, which allows significantly  more variation in its format.

Right now we provide everything except the fine-granularity digits in our strftime module, so it's possible to build a format for ... most things. I think including a wider variety of specifications is out of scope for chrono (for now) but an external crate in the chronotope organization would probably be a nice thing to experiment with.

**Comment by sanmai-NL** [comment]
A practical solution:

```rust
use chrono::offset::Utc;
use chrono::Timelike;
// Timestamp without fractional second digits
let timestamp_rfc3339 = Utc::now().with_nanosecond(0).unwrap().to_rfc3339();
```

**Comment by quodlibetor** [comment]
@sanmai-NL It's straightforward to format a timestamp without *any* fractional section by just not including the `%f` format specifier. The OP wants to include the fractional section but without trailing zeros, which is not straightforward right now.
