### ISSUE TITLE
Converting a timestamp to local time is verbose and unintuitive

### ISSUE THREAD

**Issue by johnomalley** [chronotope/chrono#200]
My (simplified) use case - build a vector of file metadata (name + modified timestamp), then sort by most recent and output a name + formatted timestamp for each one in local time.  This is a trivial problem in Java, C#, JavaScript, etc.  As far as I can tell this is what I need to do in chrono:

``` rust
fn format_time(modified: i64) -> String {
    DateTime::<Utc>::from_utc(NaiveDateTime::from_timestamp(modified, 0), Utc).with_timezone(&Local).format("%Y-%m-%d %H:%M:%S").to_string()
}
```

This took me a few hours to figure out.  Wow!  I thought Java APIs were verbose.  Maybe there's an easier way but it's not obvious from the docs.

The docs refer to `Local.from_timestamp(...)` but that does not compile (apologies if I'm missing something as I'm new to Rust).

**Comment by quodlibetor** [comment]
It is sadly the case that our `from_*` methods are poorly named and don't include `from_*` at all. The are all implemented on the [`TimeZone`](https://docs.rs/chrono/0.4.0/chrono/offset/trait.TimeZone.html) trait which is part of the chrono prelude.

But for example [this works](https://play.rust-lang.org/?gist=bd92ab7fc28b9d50100f214c43c276eb&version=stable):

```rust
extern crate chrono;

use chrono::prelude::*;

fn main() {
    println!("{}", Local.timestamp(90, 0));
}
```

and outputs: `1970-01-01 00:01:30 +00:00`. 

In fact, the only places in the chrono docs that I can find that use the extremely verbose construction that you used ([on DateTime](https://docs.rs/chrono/0.4.0/chrono/struct.DateTime.html)) immediately gives the equivalent shorter constructor.

I'm going to add an issue to create `from_*` methods (and deprecate the existing constructors) on timezone, because the current situation is extremely confusing.

**Comment by johnomalley** [comment]
Ah much better - thanks for your reply.  Closing.
