### ISSUE TITLE
README incorrectly outputting format

### ISSUE THREAD

**Issue by lancecarlson** [chronotope/chrono#212]
Currently the README says format should output a string with the seconds without decimal values:

```rust
assert_eq!(format!("{:?}", dt), "2014-11-28T12:00:09Z");
```

However, when I print out the same thing I get:

```
2018-01-23T15:52:12.922267839Z
```

Is this intentional? Am I missing something?

**Comment by lancecarlson** [comment]
Perhaps this is a serde default and out of scope of the chrono package?

**Comment by quodlibetor** [comment]
nope our README _should_ be correct. I would like to migrate to [cargo-readme](https://github.com/livioribeiro/cargo-readme) so that we don't duplicate top-level docs, but I don't recall how much of a difference our README/lib docs diverge. I'm not even sure off the top of my head if they're _similar_.

If you want to fix it to match the actual output that would be cool.

**Comment by pitdicker** [comment]
Code examples have been removed from the README in https://github.com/chronotope/chrono/pull/787.
