### ISSUE TITLE
serde performance for NaiveDateTime and DateTime<FixedOffset>

### ISSUE THREAD

**Issue by inv2004** [chronotope/chrono#224]
Hello,

I did some benchmarks for serialize/deserialize DateTime<FixedOffset> and found that time for ser/de of struct with 6 simple num fields + one DateTime<FixedOffset> is not good.

I decided that DateTime could have complicate format for ser/de and changed it to NaiveDateTime, because I expected it should be fixed-size like timestamp, but nothing changed.

time in seconds

ser | de | percent | struct type
----|----|----------| -------
0.12 | 0.11 | 100% | with nums only
0.21 | 0.29 | ~175% | with time as String
1.02 | 1.07 |  ~850% | with DateTime or NaiveDateTime 

Could you please let me know is it bug and it is possible to expect increase in performance in the future versions of the library or better to use own format if performance is important?

Thank you,

**Comment by quodlibetor** [comment]
This makes sense based on the fact that we need to actually parse the datetime. I haven't looked at the implementation in awhile, there might be some easy wins available.

FWIW you could check if using the [timestamp deserialization method](https://github.com/chronotope/chrono/blob/2a825edd5c3fc228f834bb445ff409804b9ff539/src/naive/datetime.rs#L1620) is faster, I would expect it to be.

That said, optimizations for the common case would probably be accepted, depending on how badly they impacted code understandibility.

*That* said, one of the nice things about serde is that it makes it very straightforward to write your own deserialization implementations -- the `ts_seconds` module partially exists as an example so that other crates can implement their own deserialization. If you want to write a crate like `chrono-optimized-serde` and make it usable with `#[serde(with = "chrono_optimized_serde")]` that would allow you to continue using chrono (with the compatibility benefits that brings) with whatever deserialization code you want.

**Comment by inv2004** [comment]
Timestamp does not have ms + tz. That is the binary representation of the DateTime ? Why bincode just does not save it like struct?

**Comment by inv2004** [comment]
closing:

```
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct DateTimeUtcBin (
    #[serde(with = "my_date_format")]
    pub DateTime<Utc>
);

mod my_date_format {
    use chrono::{DateTime, TimeZone, Utc};
    use serde::{Deserialize, Serializer, Deserializer};

    pub fn serialize<S>(date: &DateTime<Utc>, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        serializer.serialize_i64(date.timestamp_millis())
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<DateTime<Utc>, D::Error>
        where D: Deserializer<'de>
    {
        let i = i64::deserialize(deserializer)?;
        Ok(Utc.timestamp(i / 1000, 1_000_000 * (i % 1000) as u32))
    }
}
```
