### ISSUE TITLE
If `/etc/localtime` is updated, `Local::now()` uses the old timezone

### ISSUE THREAD

**Issue by derekdreery** [chronotope/chrono#272]
This is an issue in the `time` dependency. On linux, the syscall `tzset` is implicitly called the first time a timezone-aware syscall is made (e.g. `clock_gettime` or `localtime_r`). This uses the value of the environment variable `TZ` to work out the time zone, defaulting to `/etc/localtime`. If the timezone is changed (i.e. `/etc/localtime` now points to a different timezone), then `tzset` must explicitly be called to update the timezone information, otherwise the existing process will continue to use the timezone it cached on the previous call to `tzdata`.

I think we should do one of

 - Document this behavior, so it doesn't surprise anyone.
 - Call `tzset` before every use of the local timezone.
 - (Middle option) monitor either `/etc/localtime` and/or the `TZ` environment variable and call `tzset` if we detect a change.

**EDIT** another option

 - Only reset the timezone every <insert duration here>. Could be tracked by a global atomic version of `Duration`.

**Comment by derekdreery** [comment]
Additional info: I think that if you do `TZ="/etc/localtime"`, then that fixes the timezone unless the environment variable changes.

**Comment by quodlibetor** [comment]
Documenting the current behavior makes sense, including documenting what needs to be done for processes to get updated local times.

I'm concerned what it would look like for processes if the local timezone updates without them being aware that it *could* change. I guess it would probably look transparent, the only difference would be the way that the times are displayed? That would mostly be an issue if they are using a custom time format that does not include the timezone -- the time could jump around.

I could be convinced otherwise, but I think it would probably make sense to either provide a helper function or alternate constructor for `Local` that creates a background monitor, if users think that that kind of overhead is worth it for their use case.

**Comment by derekdreery** [comment]
@quodlibetor I think whatever we chose we should be careful that we are consistent across platforms. I was looking at the POSIX syscalls for date stuff and some of them call tzset, some do not. So it isn't necessarily even consistent on a given platform (in syscalls). As far as I can tell, in posix, the time syscalls should immediately reflect changes to `/etc/localtime`, if you want to fix your timezone set the `TZ` environment variable to override `/etc/localtime`.

I guess it would take a lot of work to make progress here, and the current solution *works*, as long as you don't care about changes, so there's little incentive to invest the time tidying up the `time` crate into a platform-abstracting crate with a well designed API.

**Comment by quodlibetor** [comment]
> there's little incentive to invest the time tidying up the time crate into a platform-abstracting crate with a well designed API.

Ha, yeah that's more or less the role of chrono, at this point. I'm not sure what other languages do for this specific case. The idea of doing an extra system call every time we get the Local time seems unnacceptable, but I agree that the current situation is not great.

**Comment by pitdicker** [comment]
As we no longer use `localtime_r` I think this issue can be closed.
