### ISSUE TITLE
Make Duration::seconds (and siblings) const fn

### ISSUE THREAD

**Issue by axos88** [chronotope/chrono#309]
This would allow to specify things like:

```const THRESHOLD: Duration = Duration::seconds(3);```

**Comment by bspeice** [comment]
I don't think this is possible in current Rust - `const fn` isn't allowed to use branches as of Rust 1.33.

**Comment by quodlibetor** [comment]
Yes, that's what I'm currently holding off on. Even once const fn is stable enough for chrono we'll need to think about how best to support them in a way that doesn't break backcompat too terribly. Chrono currently supports rust 1.13, but const fn is the strongest reason to upgrade to a new version that is upcoming. 

Obviously we'll update, but I'd like to keep things as compatible as possible, if that means adding some features or something else so that we can still work on old rustcs, I'm not sure.

**Comment by hjmallon** [comment]
`const fn` on NaiveDate and friends would also be useful.

**Comment by quodlibetor** [comment]
If anyone wants to create a PR for this behind something like an `unstable-nightly-const` feature gate I would be happy to take it. It should just be a matter of duplicating some functions and adding some `cfg` and `cfg(not)` attributes.

**Comment by csm123199** [comment]
For the googlers that came here like me, it looks like the current blocker on this issue are const-panics ([RFC](https://github.com/rust-lang/rfcs/blob/master/text/2345-const-panic.md)) ([issue](rust-lang/rust#51999)) that are triggered when doing the .expect/panic-based bounds checking on the various `Duration` constructors.

Perhaps we can introduce variants that follow stdlib functions like [checked_{mul,div,...}](https://doc.rust-lang.org/stable/std/primitive.i64.html#method.checked_mul), and return an `Option<Duration>`, with `None` meaning out-of-bounds, just like checked_mul.

Since `Duration` is re-exported from the [time](https://github.com/time-rs/time) crate, shouldn't this really be an issue there?

**Comment by zertyz** [comment]
Still not good to go on with that change?
I'd like to vote for it, because Duration constants make much sense, imho.
I actually had to quit using Duration for that and resort to ints (with a particular unit attached to their names), having to create a Duration variable every time...
Do you, authors, tought of a better way to address this scenario than using constants?
Found it nowhere in the docs...

**Comment by robjtede** [comment]
In the https://github.com/dtolnay/rustversion there's a special case for making functions const conditionally on compiler versions.

**Comment by msdrigg** [comment]
We now have const panics in rust 1.57 would it be possible to move this issue forward?

**Comment by hoon-prestolabs** [comment]
I'm waiting for this. It seems this can be reviewed relatively easily. Can we merge the @msdrigg 's  PR? Or are there other concerns?

**Comment by bestouff** [comment]
@quodlibetor does your offer still stand ?

**Comment by djc** [comment]
I'm open to merging something like this, provided it is made conditional on an opt-in feature flag (so that people who don't need this can still depend on the currently 1.32 MSRV).

**Comment by pitdicker** [comment]
Fixed in https://github.com/chronotope/chrono/pull/1337.

**Comment by bestouff** [comment]
Thanks !
