### ISSUE TITLE
Add fn `today` and `now` in `TimeZone` trait

### ISSUE THREAD

**Issue by nanocryk** [chronotope/chrono#366]
Allows to be generic over a timezone `Z: TimeZone` and call 

```rust
fn now<Z: TimeZone>(zone: Z) -> DateTime<Z> {
    zone.now()
}
```

 to get the current time.

EDIT : Changed from an associated function to a member function since we need to know the offset in `FixedOffset` to get the date.

**Comment by quodlibetor** [comment]
Does being generic over `T: TimeZone + Timelike` not work for you?

**Comment by nanocryk** [comment]
I'll explain my use case if it's more clear.

I'm using the `job_scheduler` crate, which use the `cron` crate to parse cron-like dates. `job_scheduler` use only `Utc` timezone and I need to use the `Local` timezone (since I'm in a country where there is the good idea to change timezone 2 times a year).

Thus I'm trying to figure how to contribute to `job_scheduler` to make it use any `TimeZone` instead of only `Utc`, or at least to have all dates handled in the `Local` timezone.

I though that adding these 2 functions to `TimeZone` could allow to do that, while also being a useful feature in general for this crate.

**Comment by quodlibetor** [comment]
Ah, I'm not sure that we want to add `now()` to `TimeZone` because that would force implementors of timezones to provide that, and it's not necessarily something that should be required. Most arbitrary timezones are probably being parsed (it doesn't really make sense to construct an `America/NewYork` timezone from `now()`, I don't think). 

That said, it is pretty easy to do something like what you want yourself ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=443cc49ef5bdf92434a7f017f97d2a28)):

```rust
use chrono::{Utc, Local};
use chrono::{DateTime, TimeZone};

/// Anything which can get some kind of `now` value from the system
pub trait SystemTime where Self: TimeZone {
    /// Construct a time from a timezone
    fn now() -> DateTime<Self>;
}

impl SystemTime for Utc {
    fn now() -> DateTime<Utc> {
        Utc::now()
    }
}

impl SystemTime for Local {
    fn now() -> DateTime<Local> {
        Local::now()
    }
}

fn get_time<T: SystemTime>() -> DateTime<T> {
    T::now()
}

fn main() {
    println!("{} and {}", get_time::<Utc>(), get_time::<Local>());
}
```

Plausibly adding something like a `SystemTime` trait to Chrono would be useful.

---
`NaiveDateTime` is not in any canonical format, but it does generally behave like UTC without leap seconds.

**Comment by nanocryk** [comment]
Okay, so the idea here is to provide it in an extension trait to allow implementors of `TimeZone` to not implement it (thus avoiding breaking changes). Thank you, I'll do that and will make a PR for it.

**Comment by quodlibetor** [comment]
Right. And you should be able to create that trait in your own project, too -- the fact that it works correctly in the rust playground means that it's not limited to chrono implementing it.

**Comment by quodlibetor** [comment]
I'm going to close this because the timezone trait is not the right place for these functions, and I believe the extension trait is doable.

I think it's plausible that we should add a `SystemTime` trait to chrono, but I think it might be important to think about it in terms of a more general `Clock` feature, that is just responsible for returning the current timestamp as an i64 or `(i64, u32)` tuple or something similar and can provide some conveniences like what is suggested bye the `SystemTime` trait.
