### ISSUE TITLE
Add support for RFC822

### ISSUE THREAD

**Issue by sergeysova** [chronotope/chrono#403]
I want to use chrono in the actix-web. But it removed because of chrono doesn't support parsing RFC822.

Issue: https://github.com/actix/actix-web/pull/789#issuecomment-485041718

**Comment by quodlibetor** [comment]
RFC 2822 supersedes rfc 822, fixing errata, and [chrono supports rfc 2822](https://docs.rs/chrono/0.4.11/chrono/format/enum.Fixed.html#variant.RFC2822) (and via [a dedicated method](https://docs.rs/chrono/0.4.11/chrono/struct.DateTime.html#method.parse_from_rfc2822))

AFAIK chrono has supported rfc2822 since 2014, I think that issue is just wrong.

**Comment by quodlibetor** [comment]
Feel free to re-open if there are problems with the implementation, or to comment if you've got further questions.
