### ISSUE TITLE
OutOfRangeError appears in public signatures but is a private type

### ISSUE THREAD

**Issue by quasicomputational** [chronotope/chrono#494]
Without the `time` feature, chrono uses its own definition of `Duration` in `oldtime.rs` (a private module), re-exporting it from the root of the crate. `Duration.to_std` can return an `OutOfRangeError`. However, this type is not exposed, making it impossible to match on.

This is *not* a problem with the `time` feature, as the time library exposes its version of `OutOfRangeError`.

For API parity, could the error type be exposed by chrono, please? Ideally, chrono would re-export `time::OutOfRangeError` or `oldtime::OutOfRangeError`, to allow code to be written that will deal with whatever chrono's feature set is.

**Comment by Ekleog** [comment]
FWIW, I was coming here wanting to ask the same with the default (so `time`) features, because I needed to explicitly spell out `time::OutOfRangeError` and since that point in time `dependabot` started nagging me about updating it.

Personal opinion warning: IMO, if a crate publicly exposes any type from a crate, it should also publicly reexport the whole crate, so that users don't have to manually match the versions correctly. (which, here, would I guess mean either reexposing the `time` crate when the feature is enabled or not exposing any `time` element, here considering `time::OutOfRangeError`)

**Comment by elpiel** [comment]
+1 on this one. Since the `oldtime` feature can be disabled in the future, it makes sense to export the `OutOfRangeError` to the public API, otherwise the dependency of `time` can't be avoided if you want to use something like [Duration::from_std](https://docs.rs/chrono/0.4.19/chrono/struct.Duration.html#method.from_std)
