### ISSUE TITLE
Implementing time conversions with linear equations

### ISSUE THREAD

**Issue by Plecra** [chronotope/chrono#502]
While implementing my own conversion logic I came across [this paper](http://howardhinnant.github.io/date_algorithms.html#civil_from_days), which presents lookup-free and branchless algorithms to convert between representations. 

This seems like a pretty elegant solution to me, but it looks like `chrono` is using lookup tables in its algorithms. Is this an active decision? And if so, would you mind explaining why the choice was made?

**Comment by quodlibetor** [comment]
I wasn't involved in the decision, but I believe that at the time the decision was made it was based on what other fast programming languages do. I would be open to a PR demonstrating that linear algebra could be faster than our implementation.

**Comment by pitdicker** [comment]
Chrono stores a date and time as three 32-bit values, that encode:
- the year
- the ordinal (day of the year)
- if the year is a leap year
- the day of the week of the first day of the year
- the number of seconds since midnight
- the number of nanoseconds

The alternative that your linked (very interesting) information refers to applies to an `i64` Unix timestamp with an `i32` for nanoseconds. This is a fundamentally different implementation.

The way chrono currently encodes values comes with different tradeoffs compared to Unix timestamps.

For example with a timestamp it is easy to add or subtract a duration in seconds. In chrono this would involve a modulus to add the duration to the time and the date value.
The linked example shows where chrono shines: it is easy and pretty fast to do operations on dates, where they would involve quite a number of multiplications and divisions when using timestamps.

I think both ways to store date and time can have their uses. It would be cool if there is a rust crate for both approaches. The time crate is using a similar design as chrono, but hifitime uses timestamps. So there is :smile:.

However switching chrono to using Unix timestamps doesn't seem like something we should do to me.

**Comment by Plecra** [comment]
fwiw, I intended this resource as a potential implementation of the conversion between `chrono`'s representation and timestamps: these functions implement the logic to construct and convert the year/ordinal/leap year/weekday.

At the time I was building some time handling logic. Iirc I ended up benchmarking them and choosing the algebraic implementation, but the difference is slight. The lighter binary footprint suited my needs better.
