### ISSUE TITLE
CVE-2020-26235

### ISSUE THREAD

**Issue by acim** [chronotope/chrono#602]
Please update time dependency.

 Inverse Dependency graph
time 0.1.44 (registry+https://github.com/rust-lang/crates.io-index)
└── chrono 0.4.19 (registry+https://github.com/rust-lang/crates.io-index)

**Comment by CryZe** [comment]
The CVE is wrong, 0.1 is not affected.

**Comment by Arnavion** [comment]
Actually, this conversation is founded on a wrong assumption. chrono has the issue not because of its time 0.1 dependency, but because [it directly calls `localtime_r`]() in the same way that time 0.1 does. AFAICT the code from time 0.1 that calls `localtime_r` is never called by chrono, at least not in the `Local::now` call path.

So unless I'm missing something, while it's unfortunate that the PR to update to time 0.3 hasn't been merged for a long time, it also won't actually fix the crash reported here.

**Comment by quodlibetor** [comment]
> After reading through the issues: would using a shared lock for set_var and the localtime_r invocation fix this issue?

`set_var` already takes the lock. Unfortunately last time I looked the rust stdlib does not expose the environment lock for clients (i.e., us). So we can't take the lock before calling `localtime_r`.

Even if we could, that wouldn't prevent other things that somehow affect the environment through libc from modifying it.

**Comment by Arnavion** [comment]
cargo-audit already works fine in the case of optional dependencies that aren't enabled because the corresponding feature isn't enabled, because such dependencies are not in the lockfile, so cargo-audit doesn't know about them anyway.

**Comment by tarcieri** [comment]
See https://github.com/rustsec/advisory-db/issues/288 and https://github.com/rustsec/rustsec/issues/21 for some potential options for false positive elimination

**Comment by esheppa** [comment]
As a way of moving forward with this, are either of the following two solutions palatable:

1. Remove `chrono::offset::Local` from `chrono` and put it in a new library, this would mean that only people who explicity need to use `chrono::offset::Local` would be affected by the CVE (hopefully this is a much smaller group than the total users of `chrono`). This would require an `0.5` release of `chrono` which may or may not be acceptable.
2. Make a new library, `chrono-core` or similar, which doesn't contain `chrono::offset::Local` and potentially also some other modules, specifically for libraries to depend, which would hopefully make it so only binaries are affected by the CVE, which will likely be more palatable as it is easier to enforce using or not using the `chrono::offset::Local` module in a binary than an upstream library. This would avoid an `0.5` release of `chrono` and users who want to avoid the CVE can depend only on `chrono-core`.

I've reviewed the previous discussion and haven't found mention of these options previously, however if they have already been discussed and are not optimal solutions, then please disregard this.

**Comment by Kixunil** [comment]
@esheppa see also third solution: https://github.com/chronotope/chrono/issues/499#issuecomment-1036352037

**Comment by djc** [comment]
I'm going to close this because in its current version, chrono does not call the vulnerable APIs in time 0.1. Since #478 the dependency on time is fairly minimal and in the next semver-compatible version we'll remove it entirely.

**Comment by DanielJoyce** [comment]
@djc it still looks like chrono still calls localtime_r directly, so is still vulnerable to this issue.

https://github.com/chronotope/chrono/search?q=localtime_r

One option is remove this feature, split into seperate crate, or use tz-rs crate, at least on unix.

**Comment by poliorcetics** [comment]
Now that a new release has been cut and the issue fixed, this can probably be unpinned from the issue page 🎉

**Comment by djc** [comment]
I only just added it. We're still regularly getting PRs from people who want to update the time dependency in chrono, and I would like to try and pre-empt these.

**Comment by Xuanwo** [comment]
Thank @djc! It's reborn of `chrono` project.

As this issue has been resolved, it's time for us to unpin this issue.

**Comment by HayleyDeckers** [comment]
Given the amount of reports in a short time, and the fact that everyone who runs into this with their audits will have to come and check, might it be a good idea to upgrade the dependency regardless of whether or not it is a false positive?

 #748 already seems to have done (some of ?) the work of converting the code. Are there any issues with upgrading the dependency that I'm unaware of?

**Comment by sage-msft** [comment]
For anyone else who ends up here looking for context on the fix, check out the [release notes for 0.4.20](https://github.com/chronotope/chrono/releases/tag/v0.4.20).

> Due to compatibility reasons, this release does not yet remove the time 0.1 dependency, though chrono 0.4.20 does not depend on the vulnerable parts of the time 0.1.x versions. In a future 0.5 release, we will remove the time dependency.

There have been patch releases since then, but chrono hasn't reached 0.5 yet and still has the old time dependency.

Thanks all for the progress on this!

**Comment by djc** [comment]
Note that you might/should be able to disable the dependency on time 0.1 by setting `default-features = false` (and potentially re-enabling `clock` and `std`).

**Comment by qtfkwk** [comment]
> Note that you might/should be able to disable the dependency on time 0.1 by setting `default-features = false` (and potentially re-enabling `clock` and `std`).

Totally appreciate the work to resolve this! Spend some time reviewing this today. Would like to make a small suggestion here to anyone using chrono going forward: DO NOT just run `cargo add chrono` or place `chrono = "0.4.22"` in your `Cargo.toml` file(s)... instead DO run `cargo add chrono --no-default-features -F clock` or place `chrono = { version = "0.4.22", default-features = false, features = ["clock"] }` in your `Cargo.toml` file(s). Thanks again!

**Comment by kpcyrd** [comment]
Is there a timeline for a chrono 0.5.0 release that sets the `time 0.1` dependency to off-by-default?

Thank you.

**Comment by djc** [comment]
There is no timeline. I started a release planning issue in #970. The timeline utterly depends on how much time people (including, but not limited to, the maintainers) are able/willing to spend on fixing the issues listed there.

**Comment by wez** [comment]
Please consider re-opening this as the current state is that chrono is triggering security reviews/advisories in multiple projects; it doesn't feel like a resolved/closed issue but an active concern that is generating work for many people.

**Comment by wez** [comment]
I understand that it's a painful state. I think some communication is lacking here; this issue is pinned but closed, and folks are being directed here as some kind of resolution, but there isn't a clear statement of what to do. A number of reactions have been to consider chrono dead and move to time 0.3, which feels drastic perhaps.

The self-serve path forwards appears to be:

* Update your chrono deps to use `default-features=false` so that the `oldtime` feature is removed, then explicitly add back any features that your project needs

Perhaps that recommendation could be edited into the OP at the top, along with a statement that 0.5 will take some time to release (and perhaps solicit some volunteers!) because chrono is so widely used?

Another possible resolution is to branch 0.5 from the last published 0.4 commit with the only change being that `oldtime` is removed from the default features, and publish that.  Then the mainline can be focused on 0.6 rather than 0.5.  With that approach, the dependent crates can more simply "upgrade" to resolve the security advisory.

**Comment by jplatte** [comment]
I think it's also valid to just configure your audit tool to ignore this particular CVE since IIRC chrono never called the vulnerable function in time.

**Comment by Borber** [comment]
> @wez sorry for the current state (which I inherited). Unfortunately in my opinion there is no straightforward way out of this situation other than doing the work of releasing 0.5, which, for a crate which is as popular as this one, is a pretty large and complicated project.
> 
> For now, you can disable some of the Cargo features to remove the dependency on the time 0.1 crate.
> 
> I'm also open to releasing 0.5 alphas if that's helpful to folks.

alphas please

**Comment by djc** [comment]
@FlorianUekermann wrong issue?

**Comment by djc** [comment]
@wez and others, I proposed a way forward in #1073.
