### ISSUE TITLE
Status of `serde::ts_microseconds`?

### ISSUE THREAD

**Issue by Michael-J-Ward** [chronotope/chrono#663]
Is there anything preventing the `ts_microseconds` functions to be merged?

#304 has been merged since Nov of 2020
#533 has been merged since Oct of 2021

I searched and couldn't find a discussion of what's blocking the `0.4.20` features.

**Comment by djc** [comment]
There hasn't been a release because the previous maintainer did not have much time/energy to work on chrono anymore. I have recently started as a maintainer and hopefully we can publish a release soon. However, my first priority is fixing #499 (https://rustsec.org/advisories/RUSTSEC-2020-0159). Once that is done, I will publish the next release.
