### ISSUE TITLE
Consider adding a "Default" implementation to Duration

### ISSUE THREAD

**Issue by eminence** [chronotope/chrono#717]
Would you consider having `chrono::Duration` implement `Default`, which would produce a zero-duration `Duration` ?

This would be consistent with [`std::time::Duration`](https://doc.rust-lang.org/std/time/struct.Duration.html#impl-Default)

**Comment by eminence** [comment]
Ah, I had forgotten about `oldtime`.   `chrono::Duration` already had a slightly different API from `time::Duration`.   For example `chrono::Duration` implements `Hash` but `time::Duration` does not.   (Though otherwise their APIs are nearly identical).  

Maybe chrono 0.5 could add a `impl Default for Duration` ?

**Comment by djc** [comment]
I'd be happy to add that once we straighten out the compatibility situation.

**Comment by delightfulagony** [comment]
What's the current state of this issue?

As far as I understood from @djc, the reason for not implementing Default was because `std::time::Duration` didn't implement it in `0.1.x`.

As of `0.3.17` default is implemented, does that mean this is no longer "API-Incompatible" and could be implemented?

**Comment by djc** [comment]
On the main branch (which will eventually become 0.5) we can add a `Default` implementation to what's now called `TimeDelta`. On the 0.4.x branch due to compatibility concerns that will not be viable.

You seem to be confusing the `std::time::Duration` type with the `Duration` type from the time crate. Due to compatibility, chrono 0.4.x will always (conditionally) depend on time 0.1, while chrono 0.5 does not depend on time at all.

**Comment by delightfulagony** [comment]
You're right, I mistook `std::time` with the time crate.

But if this time I checked right, as of `0.1.3` for `std::time::Duration`, [default is also implemented](https://doc.rust-lang.org/std/time/struct.Duration.html#impl-Default-for-Duration)

**Comment by djc** [comment]
Yes, but the `Duration` we expose in chrono is actually the one from the time crate, so `std::time::Duration` has no bearing on this issue.

**Comment by esheppa** [comment]
@delightfulagony - if this https://github.com/chronotope/chrono/pull/860 or a linked PR gets merged, then you will be able to use `std::time::Duration` directly, including its `Default` implementation, would that satisfy your use case?

**Comment by delightfulagony** [comment]
> Yes, but the `Duration` we expose in chrono is actually the one from the time crate, so `std::time::Duration` has no bearing on this issue.

Oh ok, so I misunderstood you, alright, thank you

> @delightfulagony - if this #860 or a linked PR gets merged, then you will be able to use `std::time::Duration` directly, including its `Default` implementation, would that satisfy your use case?

I suppose it would, in any case I changed to using the time crate that also works for my needs, and since you guys are working on `5.x.x` don't worry about it, thank you for taking the time to answer and explain :smile: 

You're both the best! :tada: :+1:

**Comment by pitdicker** [comment]
Added in https://github.com/chronotope/chrono/pull/1327.
