### ISSUE TITLE
DateTime::parse_from_str not equivalent to TimeZone::datetime_from_str

### ISSUE THREAD

**Issue by Mark-Simulacrum** [chronotope/chrono#93]
DateTime::parse_from_str will parse `Mon Mar 14 08:32:45 2016 -0700`, but TimeZone::datetime_from_str will not.

Relevant IRC conversation starts here: https://botbot.me/mozilla/rust-tools/2016-08-26/?msg=71963735&page=1

**Comment by pitdicker** [comment]
The irc logs are no longer available. But I think the issue is in how `TimeZone::datetime_from_str` works. From the documentation:
"If the to-be-parsed string includes an offset, it must match the offset of the `TimeZone`, otherwise an error will be returned."

So with `TimeZone::datetime_from_str` before parsing a string that includes an offset, you are expected to know the time zone. I.e. you have to know the offset before parsing a string as `FixedOffset`.

Also in the case of time zones like provided by `chrono_tz` parsing may fail even when you know the time zone, because the offset may have changed with a new revision of the time zone database.

I don't really see any use case where you would want to use `TimeZone::datetime_from_str` over `DateTime::parse_from_str`.

**Comment by djc** [comment]
> I don't really see any use case where you would want to use `TimeZone::datetime_from_str` over `DateTime::parse_from_str`.

Should we deprecate the shit out of it?

**Comment by pitdicker** [comment]
:rofl: With pleasure https://github.com/chronotope/chrono/pull/1251.
