### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by theduke** [chronotope/chrono#96]
Making all the date types generic over the Timezone (UTC, Local, ...) seems like a very weird design decision to me.

Why did you go this route?

I think it hurts reusability / cross library interop cumbersome, and most people probably just end up using DateTime<UTC> most of the time.

It also makes the API quite ugly in my opinion.

Something to do with performance / zero cost?

**Comment by lifthrasiir** [comment]
Genericity mainly stems from the desire for tz-aware date and time operations. Specifically, one may want to `DateTime + Duration` to work correctly. There is also a minor concern over efficiency in the case of `DateTime<UTC>`, but it is not the direct reason. The conversion between different `DateTime<Tz>` types are essentially free, though it can be made more ergonomic (probably with `Into` implementations).

There is one crucial design choice hidden there: Is it desirable to provide such operations after all? Chrono was originally designed under the assumption that `std::time` and/or libtime will be kicking around and Chrono will fill a niche, so it was a natural choice to add relatively uncommon operations. It turns out that libtime will be (eventually) discarded and `std::time` has a completely different API, and yeah it gives me a headache... The alternative would be making `DateTime<FixedOffset>` default and `TimeZone` should do other operations, which I haven't completely mapped out yet.

**Comment by quodlibetor** [comment]
I'm going to close this: Chrono is slated for review as part of the libs blitz and we can expect a bunch more community input when/if they get around to it.

As is, I like the fact that chrono currently prevents interactions between different timezones at compile time, and has caught some pretty dumb mistakes that I've made. On the other hand, treating everything as UTC internally (which is what's actually) means that the interaction isn't actually poorly defined (afaik) so we're making things more explicit when it's not 100% necessary.
